### PR TITLE
Trim whitespace from uri element text

### LINKED ISSUE #322: Whitespace preservation inconsistency
While backporting some tests from Dome to Blueprint (https://github.com/ignitionrobotics/ign-sensors/pull/33/), I noticed that there's an inconsistency with how `sdf8` and `sdf10` treat multiple whitespaces inside elements (not inside arguments). The following test fails on `sdf8` but passes on `sdf10`.

I believe this difference comes from the default behaviour of `tinyxml` versus `tinyxml2`, according to `tinyxml` documentation on [whitespace preservation](https://leethomason.github.io/tinyxml2/):  "_By default, TinyXML-2 preserves white space in a (hopefully) sane way that is almost compliant with the spec. (TinyXML-1 used a completely different model, much more similar to 'collapse'_".

It would be nice to be consistent across SDF versions. I can see arguments for each behaviour though. This is not very important for our use cases right now, but I thought we should keep track of it.

### Test

```.diff
diff --git a/src/SDF_TEST.cc b/src/SDF_TEST.cc
index 27f194ad..cca71d2e 100644
--- a/src/SDF_TEST.cc
+++ b/src/SDF_TEST.cc
@@ -696,6 +696,37 @@ TEST(SDF, WriteURIPath)
 }
 #endif  // _WIN32
 
+/////////////////////////////////////////////////
+TEST(SDF, readString)
+{
+  std::string testWorld = R"sdf(
+    <?xml version="1.0" ?>
+    <sdf version="1.5">
+      <world name="hello  world(123)">
+        <frame>
+          <name>hello  world(456)</name>
+        </frame>
+      </world>
+    </sdf>)sdf";
+
+  sdf::SDF sdfParsed;
+  sdf::initFile("root.sdf", sdfParsed.Root());
+  auto rootOriginal = sdfParsed.Root();
+  EXPECT_TRUE(sdf::readString(testWorld, rootOriginal));
+
+  EXPECT_TRUE(sdfParsed.Root()->HasElement("world"));
+  auto worldElem = sdfParsed.Root()->GetElement("world");
+  ASSERT_NE(nullptr, worldElem);
+
+  EXPECT_EQ("hello  world(123)", worldElem->Get<std::string>("name"));
+
+  EXPECT_TRUE(worldElem->HasElement("world"));
+  auto frameElem = worldElem->GetElement("frame");
+  ASSERT_NE(nullptr, frameElem);
+
+  EXPECT_EQ("hello  world(456)", frameElem->Get<std::string>("name"));
+}
+
 /////////////////////////////////////////////////
```

### Failure on `sdf8`

```
/home/chapulina/blueprint_ws/src/sdformat/src/SDF_TEST.cc:723: Failure
Value of: worldElem->HasElement("world")
  Actual: false
Expected: true
/home/chapulina/blueprint_ws/src/sdformat/src/SDF_TEST.cc:727: Failure
Expected equality of these values:
  "hello  world(456)"
  frameElem->Get<std::string>("name")
    Which is: "hello world(456)"
```

### PR DESCRIPTION
**Pull request by scpeters**
This copies the whitespace test from #359
but takes a narrower approach by only trimming
whitespace from `<uri>` element text.

Closes #322.

Signed-off-by: Steve Peters <scpeters@openrobotics.org>

### CODE REVIEW

**Review by chapulina — COMMENTED** [review]
> only trimming whitespace from <uri> element text.

While working on an `ign-sensors` PR I needed the whitespace fix within a `<topic>` field: https://github.com/ignitionrobotics/ign-sensors/pull/33#discussion_r462408029

I think it's not safe to assume that only URIs need the fix. I wouldn't be surprised to see some of these around, for example:

```
<name>
    my_robot
</name>
```

**Comment by scpeters** [comment]
> > only trimming whitespace from  element text.
> 
> While working on an `ign-sensors` PR I needed the whitespace fix within a `<topic>` field: [ignitionrobotics/ign-sensors#33 (comment)](https://github.com/ignitionrobotics/ign-sensors/pull/33#discussion_r462408029)
> 
> I think it's not safe to assume that only URIs need the fix. I wouldn't be surprised to see some of these around, for example:
> 
> ```
> <name>
>     my_robot
> </name>
> ```

I hear you, but it still feels a bit too heavy-handed to modify every xml file like this

**Comment by scpeters** [comment]
clicked the wrong button

**Comment by chapulina** [comment]
> I hear you, but it still feels a bit too heavy-handed to modify every xml file like this

I hear you too, the other PR should affect performance. My main concern at the moment is to keep the behavior backward-compatible.

Maybe there's a less invasive way of doing it. Extending your approach to all string values, maybe? I haven't checked how this affects elements like pose... Does this work, for example?

```
<pose>
1
2
3
0.1
0.2
0.3
</pose>
```

**Comment by scpeters** [comment]
> > I hear you, but it still feels a bit too heavy-handed to modify every xml file like this
> 
> I hear you too, the other PR should affect performance. My main concern at the moment is to keep the behavior backward-compatible.
> 
> Maybe there's a less invasive way of doing it. Extending your approach to all string values, maybe? I haven't checked how this affects elements like pose... Does this work, for example?
> 
> ```
> <pose>
> 1
> 2
> 3
> 0.1
> 0.2
> 0.3
> </pose>
> ```

I wrote that but then thought better of it but clicked "close with comment" by accident. I've since deleted it. I'm still thinking it through.

**Comment by scpeters** [comment]
closing in favor of #359

**Pull request closed without merging**
