### PR TITLE
Cherry-pick #312, #316 to master

### PR DESCRIPTION
**Pull request by scpeters**
This is a forward-port via cherry-pick of #312 and #316 from `sdf10`. Use rebase and merge if CI is clean.

### CODE REVIEW

**Comment by scpeters** [comment]
CI is happy after updating an expected console message in e2db237. I'll rebase and merge now

**Comment by scpeters** [comment]
actually I'm going to squash e2db237 into f4fe589 and then merge

**Comment by scpeters** [comment]
CI is happy again; I'm going to rebase and merge

**Comment by dirk-thomas** [comment]
@scpeters This pull request seem to have introduced the following compiler warnings: https://build.osrfoundation.org/job/ignition_launch-ci-master-bionic-amd64/10/

[Discovered during osrf/buildfarmer#84]

**Pull request merged**
