### PR TITLE
Backport double sided material spec

### PR DESCRIPTION
**Pull request by iche033**
backport of pull request #410

### CODE REVIEW

**Review by chapulina — APPROVED** [review]

**Comment by scpeters** [comment]
some odd windows test failures after merging with `sdf9`:

* [Build Status](https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1686/) https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1686/testReport/

~~~
1: [----------] 2 tests from DOMActor
1: [ RUN      ] DOMActor.LoadActors
  1/172 Test   #1: INTEGRATION_actor_dom ..................................Exit code 0xc0000417
***Exception:   0.09 sec
~~~

~~~
35: [----------] 1 test from DOMWorld
35: [ RUN      ] DOMWorld.LoadLights
 35/172 Test  #35: INTEGRATION_light_dom ..................................Exit code 0xc0000417
***Exception:   0.08 sec
~~~


~~~
81: [----------] 5 tests from DOMWorld
81: [ RUN      ] DOMWorld.NoName
81: No HOME defined in the environment. Will not log.
81: [       OK ] DOMWorld.NoName (47 ms)
81: [ RUN      ] DOMWorld.Duplicate
81: [       OK ] DOMWorld.Duplicate (59 ms)
81: [ RUN      ] DOMWorld.LoadIncorrectElement
81: [       OK ] DOMWorld.LoadIncorrectElement (62 ms)
81: [ RUN      ] DOMWorld.Load
 81/172 Test  #81: INTEGRATION_world_dom ..................................Exit code 0xc0000417
***Exception:   0.24 sec
~~~

~~~
85: [----------] 7 tests from DOMActor
85: [ RUN      ] DOMActor.DefaultConstruction
85: [       OK ] DOMActor.DefaultConstruction (0 ms)
85: [ RUN      ] DOMActor.CopyConstructor
85: [       OK ] DOMActor.CopyConstructor (0 ms)
85: [ RUN      ] DOMActor.CopyAssignmentOperator
85: [       OK ] DOMActor.CopyAssignmentOperator (0 ms)
85: [ RUN      ] DOMActor.MoveConstructor
85: [       OK ] DOMActor.MoveConstructor (0 ms)
85: [ RUN      ] DOMActor.MoveAssignment
85: [       OK ] DOMActor.MoveAssignment (0 ms)
85: [ RUN      ] DOMActor.CopyAssignmentAfterMove
85: [       OK ] DOMActor.CopyAssignmentAfterMove (0 ms)
85: [ RUN      ] DOMActor.Add
 85/172 Test  #85: UNIT_Actor_TEST ........................................Exit code 0xc0000417
***Exception:   0.03 sec
~~~

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
now the windows build is failing with an internal compiler error:

* [Build Status](https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1687/) https://build.osrfoundation.org/job/sdformat-ci-pr_any-windows7-amd64/1687/

I'm going to take that build machine offline and try again

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Review by scpeters — APPROVED** [review]

**Pull request merged**
