### PR TITLE
Demonstration of using utils::ImplPtr

### PR DESCRIPTION
**Pull request by mjcarroll**
A demonstration of using the new ignition-utils::ImplPtr: https://github.com/ignitionrobotics/ign-utils/pull/1

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by scpeters** [comment]
I don't think we should add a dependency to `libsdformat10`, since it's already been released

**Comment by scpeters** [comment]
and I would check with @azeey to see what he thinks

**Comment by mjcarroll** [comment]
> I don't think we should add a dependency to libsdformat10, since it's already been released

I agree, this is a quick draft to show the utility of the ImplPtr.  It should have been targeted to main.

**Comment by azeey** [comment]
Oh this is super nice!! Thanks @mjcarroll

**Comment by scpeters** [comment]
> Oh this is super nice!! Thanks @mjcarroll

yes it is way more elegant

**Comment by mjcarroll** [comment]
Superceded by #472 (and friends)

**Pull request closed without merging**
