### PR TITLE
10 ➡️  master

### PR DESCRIPTION
**Pull request by azeey**
Merge-forward from sdf10 to master. This replaces #432

### CODE REVIEW

**Comment by azeey** [comment]
https://github.com/osrf/sdformat/pull/434 updated `.github/workflows/linux-ubuntu-bionic.yml` to use prereleases, but that workflow file was deleted in https://github.com/osrf/sdformat/pull/452. Do we have a way to use prereleases in github actions with our new workflow file?

**Comment by azeey** [comment]
> Do we have a way to use prereleases in github actions with our new workflow file?

Looks like it uses gzdev which has been updated to use prereleases in https://github.com/ignition-tooling/gzdev/pull/26. I just needed to remove `.github/workflows/linux-ubuntu-bionic.yml`.

**Review by chapulina — APPROVED** [review]
Thanks for opening the PR, @azeey ! I went over all files and don't see anything out of place. CI seems happy too.

**Review by j-rivero — APPROVED** [review]
Compiles fine for me on Windows and fixed problems with lack of sky support on master.

**Pull request merged**
