### PR TITLE
parser: Use encapsulated string constants for non-file sources

### LINKED ISSUE #536: String parsing results in FilePath as `data-string` when error occurs
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build?
  * Source build, branch `sdf11`
  
  

## Description
Adding this test in `parser_TEST.cc`,
```cpp
TEST(Parser, ReadStringError)
{
  sdf::SDFPtr sdf = InitSDF();
  std::ostringstream stream;
  stream
    << "<sdf version='1.8'>"
    << "<model name=\"test\">"
    << "  <link name=\"test1\">"
    << "    <visual name=\"good\">"
    << "      <geometry>"
    << "        <box><size>1 1 1</size></box>"
    << "      </geometry>"
    << "    </visual>"
    << "  </link>"
    << "  <link>"
    << "    <visual name=\"good2\">"
    << "      <geometry>"
    << "        <box><size>1 1 1</size></box>"
    << "      </geometry>"
    << "    </visual>"
    << "  </link>"
    << "</model>"
    << "</sdf>";
  sdf::Errors errors;
  EXPECT_FALSE(sdf::readString(stream.str(), sdf, errors));
  ASSERT_NE(errors.size(), 0u);

  std::cerr << errors[0] << std::endl;

  EXPECT_EQ(errors[0].Code(), sdf::ErrorCode::ATTRIBUTE_MISSING);
  EXPECT_FALSE(errors[0].FilePath().has_value());
  EXPECT_FALSE(errors[0].LineNumber().has_value());
}
```

* Expected behavior: 

Expected `FilePath` and `LineNumber` to be missing.

```bash
Error Code 4: Msg: Required attribute[name] in element[link] is not specified in SDF.
```

* Actual behavior: 

However due to the source being set to `data-string`, we get this.

```bash
Error Code 4: [data-string:L1]:  Msg: Required attribute[name] in element[link] is not specified in SDF.
```

## Steps to reproduce

1. Add code block into `parser_TEST.cc`
2. Build.
3. Run `./build/sdformat11/src/UNIT_parser_TEST`

## Output

Gist, https://gist.github.com/aaronchongth/74c9641202dbdc4e60142a8547449a1f

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
# 🦟 Bug fix

Fixes #536, follow-up to #537
Downstream: https://github.com/ignitionrobotics/ign-gazebo/pull/794

## Summary
Takes prior revision of #537.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Updated documentation (as needed) - N/A
- [x] Updated migration guide (as needed) - N/A
- [ ] Code check passed (In source directory, run `sh tools/code_check.sh`)
- [ ] All tests passed (See
  [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+)
to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by azeey** [comment]
I think this will change behavior in a stable release. The string "data-string" is used in a stable release of [ign-gazebo](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/src/Util.cc#L289). Can we target this to `main`?

**Comment by chapulina** [comment]
> I think this will change behavior in a stable release.

True. How about keeping the string as `data-string` on this branch and updating it to `<data-string>` on `main`?

**Comment by EricCousineau-TRI** [comment]
Done! Retargeted `main`

Meta: I'm a wee bit confused on release process and expected stability for version branches and all that. Y'all got a page that explains that part?

**Review by aaronchongth — APPROVED** [review]
Thanks for quick fixes!

> Meta: I'm a wee bit confused on release process and expected stability for version branches and all that. Y'all got a page that explains that part?

I would be curious to learn more about this too

**Comment by EricCousineau-TRI** [comment]
Per VC, ABI checker failure may be due to statefulness; @azeey will try to re-run; simplest mitigation may be to ignore CI results and merge pending approval.

**Review by azeey — APPROVED** [review]

**Pull request merged**
