### PR TITLE
[Bazel] Add test fixes

### PR DESCRIPTION
**Pull request by JShep1**
`ign_TEST` is the last test that's failing, I'll hook up command line ign tomorrow (6/25) and try to sort it out

Signed-off-by: John Shepherd <john@openrobotics.org>

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Howdy @JShep1! Just as an FYI, we have this BUILD file for consuming `libsdformat` from Bazel as well:
https://github.com/RobotLocomotion/drake/blob/81793f75bb1443f36c8bab51519d3fe16d6a4005/tools/workspace/sdformat/package.BUILD.bazel
(looks like you don't need it, but just leaving it here in case)

**Comment by JShep1** [comment]
@EricCousineau-TRI Thanks!  The Drake files have certainly been helpful for us along the way as we get Ignition up and going with Bazel.  We've reused a couple of Drake's files and provided credit where we have.  The help is greatly appreciated

**Comment by EricCousineau-TRI** [comment]
Ah, gotcha, thanks! Just took a gander at https://github.com/ignitionrobotics/ign-bazel as well - sweet!

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Pull request merged**
