### PR TITLE
Bump to 10.0.0, prepare for stable release

### PR DESCRIPTION
**Pull request by scpeters**
Signed-off-by: Steve Peters <scpeters@openrobotics.org>

### CODE REVIEW

**Review by chapulina — APPROVED** [review]

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Review by azeey — APPROVED** [review]
LGTM. Should we remove the deprecated member functions `JointAxis::UseParentModelFrame` and `JointAxis::SetUseParentModelFrame`?

**Review by chapulina — CHANGES_REQUESTED** [review]
Can we wait on a resolution on https://github.com/ignitionrobotics/ign-gazebo/pull/389 before triggering the release? Just want to make sure we haven't forgot any corner cases.

CC @ahcorde

**Comment by scpeters** [comment]
I'm happy to wait. I'll close this for now

**Comment by scpeters** [comment]
> LGTM. Should we remove the deprecated member functions `JointAxis::UseParentModelFrame` and `JointAxis::SetUseParentModelFrame`?

#379

**Review by chapulina — APPROVED** [review]
:ship: it!

**Comment by scpeters** [comment]
>  it!

I just updated the changelog and will wait for CI to settle

**Pull request merged**
