### PR TITLE
10 ➡️ master

### PR DESCRIPTION
**Pull request by azeey**
I'd appreciate some scrutiny on this PR since this is my first time doing a cherry-pick forward port on sdformat. My process was:
* Create a branch from master called `10_master_reference`
* Merge `sdf10` into `10_master_reference` and fix any conflicts
* Use `git cherry -v master > cherry_list.txt` and manually go through the generated text and check if those commits have been added to `master`. If so, remove them from the list.
* Create another branch on master called `10_to_master`
* `cat cherry_list.txt | cut -d' ' -f2 | xargs git cherry-pick` and fix any conflicts
* Compare `10_to_master` and `10_master_reference` and verify that the differences left over do not need to be ported.

### CODE REVIEW

**Comment by chapulina** [comment]
Is this cherry-pick PR still under consideration, or will it be superseded by a merge-forward similar to https://github.com/osrf/sdformat/pull/445?

**Comment by scpeters** [comment]
> Is this cherry-pick PR still under consideration, or will it be superseded by a merge-forward similar to #445?

I think we can replace it with a PR using a straight merge, since that will be our approach going forward

**Comment by chapulina** [comment]
> I think we can replace it with a PR using a straight merge

Sounds good. I started working on it, but there are many conflicts and I haven't been following development of this library closely. Maybe @azeey or @scpeters can open it? Otherwise, I can try to do it by comparing to this PR. Thanks!

**Comment by azeey** [comment]
I will close this and open a merge forward PR.

**Pull request closed without merging**
