### PR TITLE
[sdf7] Changelog links to BitBucket backup

### PR DESCRIPTION
**Pull request by chapulina**
Signed-off-by: Louise Poubel <louise@openrobotics.org>

### CODE REVIEW

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by scpeters** [comment]
@chapulina there's a weird DCO failure here

if you click on DCO details: "Commit sha: 8e558ee, Author: chapulina, Committer: GitHub; Can not find "chapulina louise@openrobotics.org", in ["Louise Poubel louise@openrobotics.org", "Louise Poubel louise@openrobotics.org"]."

**Comment by chapulina** [comment]
> weird DCO failure here

Interesting, maybe it was expecting `chapulina` to match `Louise Poubel`. I think that may be the situation when the commit is done from the GitHub UI that people were mentioning earlier? I don't remember how I made that commit.

**Comment by scpeters** [comment]
ok, I'll just do a manual override

**Pull request merged**
