### PR TITLE
Cherry-pick from sdf9 to sdf10

### PR DESCRIPTION
**Pull request by scpeters**
Cherry-pick #245, #368, #369, #361 to `sdf10`. Use rebase and merge.

I've created a branch that merged sdf9 -> sdf10 with resolved conflicts. Compare the diff to confirm that these changes are all that's missing from `sdf10`:

* https://github.com/osrf/sdformat/compare/sdf10...merge_9_10_reference?expand=1

### CODE REVIEW

**Comment by scpeters** [comment]
@chapulina why didn't this get any labels?

**Comment by scpeters** [comment]
> @chapulina why didn't this get any labels?

is it because I created the PR from my fork?

**Comment by scpeters** [comment]
added labels manually

**Review by azeey — APPROVED** [review]

**Comment by chapulina** [comment]
> > @chapulina why didn't this get any labels?
> is it because I created the PR from my fork?

Yup, GitHub actions are really annoying with PRs from forks. I've been  but just [last month](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) they added a new feature that should fix. Here's an issue for tracking this: https://github.com/ignition-tooling/pr-collection-labeler/issues/4

**Pull request merged**
