### PR TITLE
[sdf9] Changelog links to BitBucket backup

### PR DESCRIPTION
**Pull request by chapulina**
Signed-off-by: Louise Poubel <louise@openrobotics.org>

### CODE REVIEW

**Comment by scpeters** [comment]
it looks like the formatting in this PR matches the changes you noted in https://github.com/osrf/sdformat/pull/233#issuecomment-613177960 that aren't yet included on master.

as I think about how to resolve these conflicts, it make me wonder if we are still going to merge branches forward? or will we use the cherry-pick strategy?

**Comment by chapulina** [comment]
> it make me wonder if we are still going to merge branches forward? or will we use the cherry-pick strategy?

I don't have a strong preference. I've been merging forward `gazebo_ros_pkgs` because that's what I'm most comfortable with, but perhaps cherry-picking could be cleaner.

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by chapulina** [comment]
> it looks like the formatting in this PR matches the changes you noted in #233 (comment) that aren't yet included on master.

See #246

**Comment by scpeters** [comment]
I just noticed an incorrect link in the API documentation and fixed it in c13f447

we should re-upload the API docs with this fix

**Pull request merged**
